# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, inputs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
#    inputs.nixos-hardware.nixosModules.dell-xps-13-9370
    inputs.nixos-hardware.nixosModules.lenovo-thinkpad-t430
 ];

  boot.initrd.availableKernelModules = [ "ohci_pci" "ehci_pci" "ahci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
#  boot.kernelParams = [
#      # HACK Disables fixes for spectre, meltdown, L1TF and a number of CPU
#      #      vulnerabilities. This is not a good idea for mission critical or
#      #      server/headless builds, but on my lonely home system I prioritize
#      #      raw performance over security.  The gains are minor.
#      "mitigations=off"
#      # Limit ZFS cache to 8gb. Sure, this system has 64gb, but I don't want
#      # this biting me when I'm running multiple VMs.
#      "zfs.zfs_arc_max=8589934592"
#    ];

  # CPU
#  nix.maxJobs = lib.mkDefault 16;
  powerManagement.cpuFreqGovernor = "ondemand";
#  hardware.cpu.intel.updateMicrocode = true;
#  hardware.cpu.amd.updateMicrocode = true;

  # Displays
#  services.xserver = {
#    monitorSection = ''
#      VendorName  "Unknown"
#      ModelName   "DELL U2515H"
#      HorizSync   30.0 - 113.0
#      VertRefresh 56.0 - 86.0
#      Option      "DPMS"
#    '';
#    screenSection = ''
#      Option "metamodes" "HDMI-0: nvidia-auto-select +1920+0, DVI-I-1: nvidia-auto-select +0+180, DVI-D-0: nvidia-auto-select +4480+180"
#      Option "SLI" "Off"
#      Option "MultiGPU" "Off"
#      Option "BaseMosaic" "off"
#      Option "Stereo" "0"
#      Option "nvidiaXineramaInfoOrder" "DFP-1"
#    '';
#  };
#
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
    };
  };

  swapDevices = [ ];

  virtualisation.virtualbox.guest.enable = true;
}
